### ISSUE TITLE
Add partials dir (subdirs) to also scan

### ISSUE THREAD

**Issue by dmmalam** [emilbayes/node-hogan#1]
Hey, great project. Currently the best hogan-express adapter.
Been playing with it and have a small suggestion.

I keep all my templates in a templates dir, and partials in a subdir ie

```
templates/layout.mu
templates/index.mu
templates/about.mu

templates/partials/analytics.mu
templates/partials/twitter.mu
```

Currently I have to prepend `{{> partials/twiiter.mu}}`. It would be cool if I could set a partials directory as an Express view options like `app.set('views partials', '.../partials'`. This would allow just using `{{> twitter}}` and it would automatically use the extension set by `view engine`.

By keeping the partials in a separate folder, it ensures I don't so something silly like include a top-level template, eg, about in index, or vice versa, ie call res.render with a partial. 

I've noticed that the library doesn't give a warning/error when it can't find a partial/layout. It should probably cb express with an error object, so that the server error/logging handling logic can pick it up.

**Comment by emilbayes** [comment]
I'll consider `'views partials'` but regarding error handling, then it should send an error object to the callback. ie:

``` javascript

var nodeHogan = require('node-hogan');

var options = {
   settings: {
      'views': __dirname+'/views/'
   }
};

nodeHogan.render('load/some/non-existent/file.html', options, function(err, html) {
   //should have err be non-null since file doesn't exist
});
```

I'll write a test case later to make sure this is what's happening

**Comment by dmmalam** [comment]
Ah, just playing with it again and it seems like the errors works as
expected.
It was probably just something else on my end masking the errors,
​

**Comment by emilbayes** [comment]
Great, I'll mark this as an enhancement then. I am sceptical about the "partials dir" idea though. I want to keep this as minimalistic as possible and keep it unbiased. However if you have any ideas for how this could be done without adding bias to the project structure I'm all ears :)

**Comment by dmmalam** [comment]
Maybe just have an option to add subdirs like
https://github.com/louischatriot/h4e.

Though I think there should be a conceptual difference between partials,
layouts and top-level templates.
I can't really think of a case where you would call render on a partial, or
layout, or include a top-level template, they all seem like errors?

Dharmesh Malam

**Comment by dmmalam** [comment]
I found when it's not reporting errors.

Say you have:

``````
layout.mu
index.mu
header.mu```

and you call `res.render('index)`

If you reference the header partial (`{{> header.mu}} from either `layout.mu`
or 'index.mu with an extension, then it will error if it doesnt exist.
However if you reference it without one, say ({{> heeeder}}, it will
silently fail.


Dharmesh Malam


On Tue, Jul 30, 2013 at 1:33 PM, Dharmesh Malam <dmmalam@gmail.com> wrote:

> Maybe just have an option to add subdirs like
> https://github.com/louischatriot/h4e.
>
> Though I think there should be a conceptual difference between partials,
> layouts and top-level templates.
> I can't really think of a case where you would call render on a partial,
> or layout, or include a top-level template, they all seem like errors?
>
> Dharmesh Malam
>
>
> On Tue, Jul 30, 2013 at 11:21 AM, Emil Bay <notifications@github.com>wrote:
>
>> Great, I'll mark this as an enhancement then. I am sceptical about the
>> "partials dir" idea though. I want to keep this as minimalistic as possible
>> and keep it unbiased. However if you have any ideas for how this could be
>> done without adding bias to the project structure I'm all ears :)
>>
>> —
>> Reply to this email directly or view it on GitHub<https://github.com/tixz/node-hogan/issues/1#issuecomment-21781877>
>> .
>>
>
>
``````
